### ISSUE TITLE
"Abort trap: 6" on Aggregate function

### ISSUE THREAD

**Issue by geodatup** [etalab/geozones#39]
I get abort error when I try to launch aggregate function manualy (next to download and load)

`(p3-env) imac-de-zugi-r:geozones-master R$ geozones aggregate
>> 
Perform zones aggregations.

Building aggregate "Metropolitan France" (level=country-subset, code=fr:metro)
No geometry for []
Building aggregate "DROM" (level=country-subset, code=fr:drom)
No geometry for []
Building aggregate "DROM-COM" (level=country-subset, code=fr:dromcom)
No geometry for []
Building aggregate "World" (level=country-group, code=world)
Assertion failed: (!"should never be reached"), function itemsTree, file AbstractSTRtree.cpp, line 371.
Abort trap: 6
`

This is my first attempt to try the geozone tools. I ran it under MacOS.

**Comment by geodatup** [comment]
I have error with **arrondissements-municipaux-20160128.shp**
when I extracting data to MongoDb but I am not sure it is the cause of the problem 
 and nothing load for country-group, country-subset, level fr:region
but some with other level ... I don't know why.

```
Processing level "country-group"
Loaded 0 zones for level country-group
Processing level "country"
Extracting 177 elements from ne_110m_admin_0_countries_lakes.zip => ne_110m_admin_0_countries_lakes.shp (ESRI Shapefile +init=epsg:4326)
Loaded 177 zones for level country from file downloads/ne_110m_admin_0_countries_lakes.zip
Loaded 177 zones for level country
Processing level "country-subset"
Loaded 0 zones for level country-subset
Processing level "fr:region"
Extracting 27 elements from regions-20140306-100m-shp.zip => regions-20140306-100m.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:region from file downloads/regions-20140306-100m-shp.zip
Extracting 18 elements from regions-20161121-shp.zip => regions-20161121.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:region from file downloads/regions-20161121-shp.zip
Loaded 0 zones for level fr:region
Processing level "fr:epci"
Extracting 2134 elements from epci-20150303-100m-shp.zip => epci-20150303-100m.shp (ESRI Shapefile +init=epsg:4326)
Loaded 2134 zones for level fr:epci from file downloads/epci-20150303-100m-shp.zip
Loaded 2134 zones for level fr:epci
Processing level "fr:departement"
Extracting 102 elements from departements-20170102-simplified.zip => departements-20170102.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:departement from file downloads/departements-20170102-simplified.zip
Loaded 0 zones for level fr:departement
Processing level "fr:collectivite"
Extracting 246 elements from TM_WORLD_BORDERS-0.3.zip => TM_WORLD_BORDERS-0.3.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:collectivite from file downloads/TM_WORLD_BORDERS-0.3.zip
Loaded 0 zones for level fr:collectivite
Processing level "fr:commune"
Extracting 35419 elements from communes-20170111-shp.zip => communes-20170112.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:commune from file downloads/communes-20170111-shp.zip
Extracting 35888 elements from communes-20160119-shp.zip => communes-20160119.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:commune from file downloads/communes-20160119-shp.zip
Extracting 36701 elements from communes-20150101-100m-shp.zip => communes-20150101-100m.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:commune from file downloads/communes-20150101-100m-shp.zip
Extracting 36680 elements from communes-20131220-100m-shp.zip => communes-20131220-100m.shp (ESRI Shapefile +init=epsg:4326)
Loaded 0 zones for level fr:commune from file downloads/communes-20131220-100m-shp.zip
Extracting 45 elements from arrondissements-municipaux-20160128-shp.zip => arrondissements-municipaux-20160128.shp (ESRI Shapefile +init=epsg:4326)
Error extracting polygon OrderedDict([('insee', '69385'), ('nom', 'Lyon 5e Arrondissement'), ('wikipedia', 'fr:5e arrondissement de Lyon'), ('surf_ha', 618.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69389'), ('nom', 'Lyon 9e Arrondissement'), ('wikipedia', 'fr:9e arrondissement de Lyon'), ('surf_ha', 753.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69386'), ('nom', 'Lyon 6e Arrondissement'), ('wikipedia', 'fr:6e arrondissement de Lyon'), ('surf_ha', 377.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69387'), ('nom', 'Lyon 7e Arrondissement'), ('wikipedia', 'fr:7e arrondissement de Lyon'), ('surf_ha', 959.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75115'), ('nom', 'Paris 15e Arrondissement'), ('wikipedia', 'fr:15e arrondissement de Paris'), ('surf_ha', 851.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75107'), ('nom', 'Paris 7e Arrondissement'), ('wikipedia', 'fr:7e arrondissement de Paris'), ('surf_ha', 409.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13210'), ('nom', 'Marseille 10e Arrondissement'), ('wikipedia', 'fr:10e arrondissement de Marseille'), ('surf_ha', 1078.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13212'), ('nom', 'Marseille 12e Arrondissement'), ('wikipedia', 'fr:12e arrondissement de Marseille'), ('surf_ha', 1400.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13209'), ('nom', 'Marseille 9e Arrondissement'), ('wikipedia', 'fr:9e arrondissement de Marseille'), ('surf_ha', 6328.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13202'), ('nom', 'Marseille 2e Arrondissement'), ('wikipedia', 'fr:2e arrondissement de Marseille'), ('surf_ha', 498.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13216'), ('nom', 'Marseille 16e Arrondissement'), ('wikipedia', 'fr:16e arrondissement de Marseille'), ('surf_ha', 1624.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13208'), ('nom', 'Marseille 8e Arrondissement'), ('wikipedia', 'fr:8e arrondissement de Marseille'), ('surf_ha', 1944.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13201'), ('nom', 'Marseille 1er Arrondissement'), ('wikipedia', 'fr:1er arrondissement de Marseille'), ('surf_ha', 177.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13215'), ('nom', 'Marseille 15e Arrondissement'), ('wikipedia', 'fr:15e arrondissement de Marseille'), ('surf_ha', 1685.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13207'), ('nom', 'Marseille 7e Arrondissement'), ('wikipedia', 'fr:7e arrondissement de Marseille'), ('surf_ha', 576.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69383'), ('nom', 'Lyon 3e Arrondissement'), ('wikipedia', 'fr:3e arrondissement de Lyon'), ('surf_ha', 637.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13214'), ('nom', 'Marseille 14e Arrondissement'), ('wikipedia', 'fr:14e arrondissement de Marseille'), ('surf_ha', 1637.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13211'), ('nom', 'Marseille 11e Arrondissement'), ('wikipedia', 'fr:11e arrondissement de Marseille'), ('surf_ha', 3339.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13213'), ('nom', 'Marseille 13e Arrondissement'), ('wikipedia', 'fr:13e arrondissement de Marseille'), ('surf_ha', 2800.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13206'), ('nom', 'Marseille 6e Arrondissement'), ('wikipedia', 'fr:6e arrondissement de Marseille'), ('surf_ha', 205.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13205'), ('nom', 'Marseille 5e Arrondissement'), ('wikipedia', 'fr:5e arrondissement de Marseille'), ('surf_ha', 218.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13204'), ('nom', 'Marseille 4e Arrondissement'), ('wikipedia', 'fr:4e arrondissement de Marseille'), ('surf_ha', 288.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '13203'), ('nom', 'Marseille 3e Arrondissement'), ('wikipedia', 'fr:3e arrondissement de Marseille'), ('surf_ha', 254.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75108'), ('nom', 'Paris 8e Arrondissement'), ('wikipedia', 'fr:8e arrondissement de Paris'), ('surf_ha', 388.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75103'), ('nom', 'Paris 3e Arrondissement'), ('wikipedia', 'fr:3e arrondissement de Paris'), ('surf_ha', 117.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69384'), ('nom', 'Lyon 4e Arrondissement'), ('wikipedia', 'fr:4e arrondissement de Lyon'), ('surf_ha', 292.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69388'), ('nom', 'Lyon 8e Arrondissement'), ('wikipedia', 'fr:8e arrondissement de Lyon'), ('surf_ha', 667.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75104'), ('nom', 'Paris 4e Arrondissement'), ('wikipedia', 'fr:4e arrondissement de Paris'), ('surf_ha', 160.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75111'), ('nom', 'Paris 11e Arrondissement'), ('wikipedia', 'fr:11e arrondissement de Paris'), ('surf_ha', 366.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75110'), ('nom', 'Paris 10e Arrondissement'), ('wikipedia', 'fr:10e arrondissement de Paris'), ('surf_ha', 289.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75105'), ('nom', 'Paris 5e Arrondissement'), ('wikipedia', 'fr:5e arrondissement de Paris'), ('surf_ha', 253.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69381'), ('nom', 'Lyon 1er Arrondissement'), ('wikipedia', 'fr:1er arrondissement de Lyon'), ('surf_ha', 152.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '69382'), ('nom', 'Lyon 2e Arrondissement'), ('wikipedia', 'fr:2e arrondissement de Lyon'), ('surf_ha', 338.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75102'), ('nom', 'Paris 2e Arrondissement'), ('wikipedia', 'fr:2e arrondissement de Paris'), ('surf_ha', 99.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75113'), ('nom', 'Paris 13e Arrondissement'), ('wikipedia', 'fr:13e arrondissement de Paris'), ('surf_ha', 714.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75112'), ('nom', 'Paris 12e Arrondissement'), ('wikipedia', 'fr:12e arrondissement de Paris'), ('surf_ha', 1631.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75117'), ('nom', 'Paris 17e Arrondissement'), ('wikipedia', 'fr:17e arrondissement de Paris'), ('surf_ha', 567.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75109'), ('nom', 'Paris 9e Arrondissement'), ('wikipedia', 'fr:9e arrondissement de Paris'), ('surf_ha', 217.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75120'), ('nom', 'Paris 20e Arrondissement'), ('wikipedia', 'fr:20e arrondissement de Paris'), ('surf_ha', 598.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75114'), ('nom', 'Paris 14e Arrondissement'), ('wikipedia', 'fr:14e arrondissement de Paris'), ('surf_ha', 560.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75116'), ('nom', 'Paris 16e Arrondissement'), ('wikipedia', 'fr:16e arrondissement de Paris'), ('surf_ha', 1637.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75101'), ('nom', 'Paris 1er Arrondissement'), ('wikipedia', 'fr:1er arrondissement de Paris'), ('surf_ha', 181.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75119'), ('nom', 'Paris 19e Arrondissement'), ('wikipedia', 'fr:19e arrondissement de Paris'), ('surf_ha', 678.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75118'), ('nom', 'Paris 18e Arrondissement'), ('wikipedia', 'fr:18e arrondissement de Paris'), ('surf_ha', 599.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Error extracting polygon OrderedDict([('insee', '75106'), ('nom', 'Paris 6e Arrondissement'), ('wikipedia', 'fr:6e arrondissement de Paris'), ('surf_ha', 216.0), ('type', 'arrondissement municipal'), ('start_date', ''), ('end_date', '')])
Traceback (most recent call last):
  File "/Users/R/Projets/geozones-master/geozones/model.py", line 130, in process_dataset
    zone = extractor(db, polygon)
  File "/Users/R/Projets/geozones-master/geozones/france/__init__.py", line 250, in extract_french_arrondissements
    zone['wikipedia'] = unicodify(props['wikipedia'])
TypeError: 'NoneType' object does not support item assignment

Loaded 0 zones for level fr:commune from file downloads/arrondissements-municipaux-20160128-shp.zip
Loaded 0 zones for level fr:commune
Processing level "fr:arrondissement"
Extracting 342 elements from arrondissements-20131220-100m-shp.zip => arrondissements-20131220-100m.shp (ESRI Shapefile +init=epsg:4326)
Loaded 342 zones for level fr:arrondissement from file downloads/arrondissements-20131220-100m-shp.zip
Loaded 342 zones for level fr:arrondissement
```
